version: "3"
services:
  etcd:
    image: quay.io/coreos/etcd:v3.1.7
    hostname: etcd
    ports:
        - 23791:2379
        - 23801:2380
    environment:
        ETCD_NAME: infra1
        ETCD_INITIAL_ADVERTISE_PEER_URLS: http://etcd:2380
        ETCD_INITIAL_CLUSTER: infra1=http://etcd:2380
        ETCD_INITIAL_CLUSTER_STATE: new
        ETCD_INITIAL_CLUSTER_TOKEN: etcd-tasting-01
        ETCD_LISTEN_CLIENT_URLS: http://etcd:2379,http://localhost:2379
        ETCD_LISTEN_PEER_URLS: http://etcd:2380
        ETCD_ADVERTISE_CLIENT_URLS: http://etcd:2379
    healthcheck:
      disable: true
  controller:
    image: qnib/uplain-slurm
    hostname: "{{.Service.Name}}-{{.Task.Slot}}"
    environment:
      - SLURM_IS_CTLD=true
  worker:
    image: qnib/uplain-slurm
    hostname: "{{.Service.Name}}-{{.Task.Slot}}"
    deploy:
      replicas: 16
